---
name: Build Hoods

# 📜 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build_macOS:
    name: Build macOS
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Output XCode and Swift version
        run: |
          xcrun xcodebuild -version
          xcrun swift --version
      - name: Build debug version
        run: |
          make build
      - name: Test debug version
        run: |
          make test

  build_iOS:
    name: Build iOS
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Output XCode and Swift version
        run: |
          xcrun xcodebuild -version
          xcrun swift --version
      - name: Show destinations
        run: xcrun xcodebuild -showdestinations -scheme Hoods
      - name: Build debug version
        run: |
          xcrun xcodebuild -skipMacroValidation -skipPackagePluginValidation build -scheme Hoods -destination generic/platform=ios
      - name: Test debug version
        run: |
          xcrun xcodebuild -skipMacroValidation -skipPackagePluginValidation test -scheme Hoods -destination 'platform=iOS Simulator,name=iPhone 14'
